#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..


# Run Homebrew installation through the Brewfile
echo "> brew bundle"

brew bundle


echo "> intalling all topic install scripts.."
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

printf "\r\033[2K  [ \033[00;32mOK\033[0m ] dot - Everything up to date\n"