#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..


# Run Homebrew installation through the Brewfile
echo "> brew bundle"

brew bundle

# PS3='Which environment do you want to install packages for? '
# options=("Private" "Work" "Private + Work")
# select opt in "${options[@]}"
# do
#     case $opt in
#         "Private")
#             echo "> Installing for only $opt use"
#             brew bundle --file=./Brewfile;
#             brew bundle install --file=./priv/Brewfile;
            
#             sepinstaller
#             break
#             ;;
#         "Work")
#             echo "> Installing for only $opt use"
#             brew bundle
#             brew bundle --file=./Brewfile.work
            
#             sepinstaller
#             break
#             ;;
#         "Private + Work")
#             echo "> Installing for $opt use"
#             brew bundle
#             brew bundle --file=./Brewfile.private
#             brew bundle --file=./Brewfile.work

#             sepinstaller
#             break
#             ;;
#         *) echo "invalid option. try again";;
#     esac
# done

echo "> intalling all topic install scripts.."
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

printf "\r\033[2K  [ \033[00;32mOK\033[0m ] dot - Everything up to date\n"